design:
  lower_bound: -1.0
  upper_bound: 1.0
  dimensionality_lower_bound: 2
  dimensionality_upper_bound: 5

function:
  noise: 0.0

optimizers:
  optimizers_names:
    [
      Adam,
      SGD,
      CG,
      CMAES,
      SimulatedAnnealing,
      LBFGSB,
      NelderMead,
      PSO,
      RandomSearch,
      SGA,
      XNES,
      RMSprop,
      Nadam,
      Adamax,
      Ftrl,
    ]

sampler:
  sampler_name: RandomUniform
  number_of_samples: 30

execution:
  number_of_functions: 1
  iterations: 100
  realizations: 1
  parallelization: True
