hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +trial_number: range(1)
  sweep:
    dir: outputs/default/${optimizer.optimizer_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: trial_${trial_number}
  job:
    chdir: True
  # hydra_logging: disabled
  # job_logging: disabled

design:
  lower_bound: 0.0
  upper_bound: 1.0
  dimensionality: 2

function:
  fidelity_values: [0.5, 1.0]
  costs: [0.5, 1.0]
  noise: None

optimizer:
  optimizer_name: MFBayesianOptimizationTorch

sampler:
  sampler_name: SobolSequence
  numbers_of_samples: [10, 5]

execution:
  iterations: 1
  budget: 10