"""AgentOptimizer, ClaudeSDKAgent, and the StrategizerImplementerOptimizer.

This module provides the agentic optimization layer for f3dasm.  Three
classes are defined:

- ``AgentOptimizer`` — abstract subclass of ``Optimizer`` that owns the
  turn-loop scaffolding, provenance recording, and artifact update logic.
- ``ClaudeSDKAgent`` — a concrete ``Agent`` wrapping the Anthropic Claude
  Agent SDK session.
- ``StrategizerImplementerOptimizer`` — the Level-1 two-agent topology
  (Strategizer proposes a strategy; Implementer executes it).

The ``Agent`` protocol is also defined here so that test stubs can satisfy
it without importing any SDK.
"""
#                                                                       Modules
# =============================================================================
from __future__ import annotations

# Standard
import json
import logging
import shutil
import warnings
from abc import abstractmethod
from collections.abc import Callable
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional, Protocol

# Local
from ..core import DataGenerator, Optimizer
from ..experimentdata import ExperimentData
from .agent_dataclasses import (
    ObjectiveDirection,
    OutputSpec,
    ParameterSpec,
    ProblemSchema,
    Strategy,
    StrategySpec,
    TurnRecord,
)
from .agent_tools import (
    make_ask_strategizer,
    make_emit_strategy,
    make_get_problem_schema,
    make_list_strategies,
    make_read_artifact,
    make_run_strategy,
    make_summarize_experiment_data,
)
from .artifact_producers import (
    SEED_TURN,
    coverage_summary,
    last_5_rationales,
    objective_summary,
)
from .strategies import default_registry

#                                                          Authorship & Credits
# =============================================================================
__author__ = "Elvis Aguero (elvis_alexander_aguero_vera@brown.edu)"
__credits__ = ["Elvis Aguero"]
__status__ = "Experimental"
# =============================================================================

logger = logging.getLogger("f3dasm.agentic")


# =============================================================================
# Module-level helper: replicate script generator
# =============================================================================


def _build_replicate_script(
    calls_repr: str,
    objective_name: str,
    direction: str,
) -> str:
    """Return the source of the auto-generated ``replicate.py`` script.

    Building the script at module level avoids the ``textwrap.dedent``
    pitfall: when multi-line f-string interpolations (e.g. the
    JSON-serialised strategy-calls list) introduce lines with less
    leading whitespace than the surrounding template, ``dedent`` has
    no common prefix to strip and leaves all indentation intact.

    Parameters
    ----------
    calls_repr : str
        JSON-serialised list of ``(name, n_steps, params)`` triples.
    objective_name : str
        Name of the scalar objective output column.
    direction : str
        ``'maximize'`` or ``'minimize'``.

    Returns
    -------
    str
        Full Python source code for ``replicate.py``.
    """

    lines: list[str] = [
        '"""Replicate the agentic run without invoking any LLM.',
        "",
        "This script was auto-generated by",
        "``AgentOptimizer.write_deliverable()``.",
        "",
        "It loads the final ExperimentData snapshot, then replays every",
        "strategy_calls triple recorded in turn_log.jsonl using the",
        "strategy adapters from f3dasm.agentic.  No LLM is called.",
        "The best design is printed to stdout.",
        "",
        "Usage",
        "-----",
        "python replicate.py",
        '"""',
        "from __future__ import annotations",
        "",
        "import sys",
        "from pathlib import Path",
        "",
        "# Locate the deliverable directory (same folder as this script).",
        "_DELIV_DIR = Path(__file__).resolve().parent",
        "",
        "# Insert the f3dasm src path if running from the repo.",
        "_REPO_ROOT = _DELIV_DIR",
        "for _ in range(6):",
        "    candidate = _REPO_ROOT / 'src'",
        "    if (candidate / 'f3dasm').exists():",
        "        sys.path.insert(0, str(candidate))",
        "        break",
        "    _REPO_ROOT = _REPO_ROOT.parent",
        "",
        "from f3dasm import ExperimentData  # noqa: E402",
        "from f3dasm.agentic import default_registry  # noqa: E402",
        "",
        "# Strategy calls recorded during the original run, in order.",
        f"_STRATEGY_CALLS = {calls_repr}",
        "",
        "",
        "def _best_design(",
        "    data: ExperimentData,",
        "    objective_name: str,",
        "    direction: str,",
        ") -> dict:",
        '    """Return the best design from the dataset."""',
        "    best_val = None",
        "    best_row: dict = {}",
        "    for idx, sample in data.data.items():",
        "        obj = sample._output_data.get(objective_name)",
        "        if obj is None:",
        "            continue",
        "        try:",
        "            obj_f = float(obj)",
        "        except (TypeError, ValueError):",
        "            continue",
        "        if obj_f != obj_f:",
        "            continue",
        "        if best_val is None:",
        "            improved = True",
        '        elif direction == "maximize" and obj_f > best_val:',
        "            improved = True",
        '        elif direction == "minimize" and obj_f < best_val:',
        "            improved = True",
        "        else:",
        "            improved = False",
        "        if improved:",
        "            best_val = obj_f",
        "            best_row = {",
        '                "experiment_id": idx,',
        '                "inputs": dict(sample._input_data),',
        '                "outputs": dict(sample._output_data),',
        "            }",
        "    return best_row",
        "",
        "",
        "def main() -> None:",
        '    """Load the snapshot and print the best design."""',
        "",
        "    data_dir = _DELIV_DIR / 'experiment_data'",
        "    data = ExperimentData.from_file(data_dir)",
        "",
        "    # Replay strategy calls (no LLM).",
        "    adapters, _ = default_registry()",
        "    for name, n_steps, params in _STRATEGY_CALLS:",
        "        if name not in adapters:",
        "            print(",
        "                f'WARNING: strategy {name!r} not found in '",
        "                'default_registry; skipping.'",
        "            )",
        "            continue",
        "        # Adapters: adapter(data, n_steps, params).",
        "        try:",
        "            adapters[name](data, n_steps, params)",
        "        except Exception as exc:",
        "            print(",
        "                f'WARNING: strategy {name!r} raised '",
        "                f'{type(exc).__name__}: {exc}'",
        "            )",
        "",
        "    best = _best_design(",
        f'        data, "{objective_name}", "{direction}"',
        "    )",
        "    if not best:",
        "        print('No best design found.')",
        "        return",
        "",
        "    print('Best design:')",
        "    print(f\"  experiment_id : {best['experiment_id']}\")",
        '    for col, val in best["inputs"].items():',
        "        print(f'  {col:25s}: {val}')",
        '    for col, val in best["outputs"].items():',
        "        print(f'  {col:25s}: {val}')",
        "",
        "",
        'if __name__ == "__main__":',
        "    main()",
        "",
    ]
    return "\n".join(lines)


# =============================================================================
# Agent protocol
# =============================================================================


class Agent(Protocol):
    """Protocol that every peer agent must satisfy.

    A persistent session object that receives a string message and a list
    of tool callables and returns the final assistant message as a string.
    Conversation history is maintained internally across ``send`` calls.

    Attributes
    ----------
    name : str
        Stable identifier used as a key in ``AgentOptimizer.agents``.
    """

    name: str

    def send(self, message: str, tools: list) -> str:
        """Dispatch a message to the agent and return its response.

        Parameters
        ----------
        message : str
            The orchestrator's turn message.
        tools : list
            Per-turn tool callables to expose to the agent.

        Returns
        -------
        str
            Final assistant message text; must contain a ``## Rationale``
            section for the turn to be recorded as successful.
        """
        ...


# =============================================================================
# AgentExecutionError
# =============================================================================


class AgentExecutionError(RuntimeError):
    """Raised when three consecutive agent turns all return ``result='error'``.

    Parameters
    ----------
    message : str
        Human-readable description of the failure.
    """

    pass


# =============================================================================
# AgentOptimizer
# =============================================================================


class AgentOptimizer(Optimizer):
    """Abstract base for agentic optimizers in the agentic-f3dasm layer.

    Subclasses implement ``call()`` to define the inter-agent topology
    (e.g. Strategizer → Implementer).  The base class owns the turn-loop
    scaffolding: building tools, dispatching agent sessions, extracting
    rationales, recording ``TurnRecord``s, and updating the
    ``AnalysisBase`` artifacts.

    Parameters
    ----------
    physics_context : str
        Day-1 problem briefing shown to agents in their system prompts.
    output_columns : dict[str, OutputSpec]
        Typed metadata for every output column.  Supplied explicitly
        because ``Domain`` does not carry kind/categories metadata.
    forbidden_extra : list of str, optional
        Additional parameter names to add to the schema's forbidden list
        beyond the constant parameters auto-detected from ``Domain``.
    objective_direction : {'minimize', 'maximize'}, default 'maximize'
        Direction of optimization for the objective column.
    """

    def __init__(
        self,
        physics_context: str,
        output_columns: dict[str, OutputSpec],
        forbidden_extra: list[str] = (),
        objective_direction: ObjectiveDirection = "maximize",
    ) -> None:
        """Initialise the base optimizer with problem context.

        Parameters
        ----------
        physics_context : str
            Day-1 problem briefing shown to agents.
        output_columns : dict[str, OutputSpec]
            Typed metadata for every output column.
        forbidden_extra : list of str, optional
            Extra forbidden parameter names.
        objective_direction : {'minimize', 'maximize'}, default 'maximize'
            Direction of optimization.
        """

        self._physics_context = physics_context
        self._output_columns = dict(output_columns)
        self._forbidden_extra = list(forbidden_extra)
        self._objective_direction: ObjectiveDirection = objective_direction

        # These are populated by arm().
        self.turn_log: list[TurnRecord] = []
        self.analysis_base: dict[str, str] = {}
        self.agents: dict[str, Agent] = {}

    # ------------------------------------------------------------------
    # arm
    # ------------------------------------------------------------------

    def arm(
        self,
        data: ExperimentData,
        data_generator: DataGenerator,
        input_name: str,
        output_name: str,
    ) -> None:
        """Prepare the optimizer for a run.

        Registers the ``__turn`` output column on the domain, stamps
        pre-existing rows with ``SEED_TURN``, builds ``ProblemSchema`` and
        the strategy registry, and initialises ``AnalysisBase``.

        Parameters
        ----------
        data : ExperimentData
            The shared dataset.  Modified in place to register ``__turn``.
        data_generator : DataGenerator
            The evaluator that will be called by strategy adapters.
        input_name : str
            Name of the input parameter group (forwarded to subclasses).
        output_name : str
            Name of the scalar objective output column.
        """

        self.data_generator = data_generator
        self.input_name = input_name
        self.output_name = output_name
        self.data_domain = data.domain

        # Register __turn as an output column so f3dasm's schema-bound
        # ExperimentData can accept it on every new row.
        data.domain.add_output("__turn", to_disk=False, exist_ok=True)

        # Stamp all pre-existing (seed) rows with SEED_TURN so narrate()
        # can skip them cleanly.
        for sample in data.data.values():
            sample._output_data["__turn"] = SEED_TURN

        # Build the ProblemSchema from the live Domain.
        self.problem_schema = self._build_problem_schema(
            data=data,
            output_name=output_name,
        )

        # Build the strategy registry (adapters + specs).
        self.strategy_adapters, self.strategy_specs = default_registry()

        # Initialise AnalysisBase by running the three producers on the
        # seed data and the (empty) turn log.
        self.analysis_base = {
            "objective_summary": objective_summary(
                data, self.problem_schema, self.turn_log
            ),
            "coverage_summary": coverage_summary(
                data, self.problem_schema, self.turn_log
            ),
            "last_5_rationales": last_5_rationales(
                data, self.problem_schema, self.turn_log
            ),
        }

    # ------------------------------------------------------------------
    # call (abstract)
    # ------------------------------------------------------------------

    @abstractmethod
    def call(
        self, data: ExperimentData, n_iterations: int, **kwargs: Any
    ) -> ExperimentData:
        """Run the agentic loop for at most ``n_iterations`` turns.

        Parameters
        ----------
        data : ExperimentData
            The shared dataset.
        n_iterations : int
            Maximum number of logical iterations.
        **kwargs : Any
            Topology-specific extra arguments.

        Returns
        -------
        ExperimentData
            The updated (mutated-in-place) dataset.
        """

        ...

    # ------------------------------------------------------------------
    # _execute_turn
    # ------------------------------------------------------------------

    def _execute_turn(
        self,
        turn_id: int,
        agent_name: str,
        message: str,
        data: ExperimentData,
    ) -> ExperimentData:
        """Execute a single agent turn and record its provenance.

        Parameters
        ----------
        turn_id : int
            Monotonically increasing turn counter.
        agent_name : str
            Key into ``self.agents``.
        message : str
            The orchestrator's turn message sent to the agent.
        data : ExperimentData
            The shared dataset (mutated in place by ``run_strategy``).

        Returns
        -------
        ExperimentData
            The dataset (same object, mutated in place).
        """

        timestamp = datetime.now(timezone.utc).isoformat()

        # Build per-turn mutable accumulators.
        strategy_calls: list[tuple[str, int, dict]] = []
        emit_slot: list[Strategy] = []

        # Build the common read-only tools for all agents.
        read_tools = [
            make_get_problem_schema(self.problem_schema),
            make_list_strategies(self.strategy_specs),
            make_summarize_experiment_data(data, self.problem_schema),
            make_read_artifact(self.analysis_base),
        ]

        # Build role-specific write tools.
        if agent_name == "strategizer":
            role_tools = [
                make_emit_strategy(self.strategy_specs, emit_slot),
            ]
        else:
            # Implementer role: run_strategy + ask_strategizer.
            followup_budget: list[int] = [self.max_followups]
            role_tools = [
                make_run_strategy(
                    adapters=self.strategy_adapters,
                    specs=self.strategy_specs,
                    data=data,
                    domain=self.data_domain,
                    data_generator=self.data_generator,
                    objective_name=self.output_name,
                    turn_id=turn_id,
                    strategy_calls_accumulator=strategy_calls,
                ),
                make_ask_strategizer(
                    dispatch_fn=self._followup_dispatch,
                    budget=followup_budget,
                ),
            ]

        tools = read_tools + role_tools

        # Dispatch the agent session.
        response = self.agents[agent_name].send(message, tools=tools)

        # Extract the rationale from the ## Rationale markdown section.
        rationale, result = self._extract_rationale(response)

        # Retrieve followup question if the agent called ask_strategizer.
        followup_question: Optional[str] = None
        if agent_name != "strategizer":
            # Scan for evidence of a followup in the strategy_calls;
            # the question itself is not recoverable from the closure here
            # so leave it None (Level-2 concern: transcript parsing).
            pass

        # Determine emitted strategy for Strategizer records.
        emitted_strategy: Optional[Strategy] = None
        if agent_name == "strategizer" and emit_slot:
            emitted_strategy = emit_slot[0]

        # Diff: query rows added during this turn by checking __turn stamp.
        experiment_ids = [
            idx
            for idx, sample in data.data.items()
            if sample._output_data.get("__turn") == turn_id
        ]

        # Append the TurnRecord to the log.
        record = TurnRecord(
            turn_id=turn_id,
            timestamp=timestamp,
            agent_name=agent_name,
            rationale=rationale,
            strategy_calls=list(strategy_calls),
            emitted_strategy=emitted_strategy,
            followup_question=followup_question,
            experiment_ids=experiment_ids,
            result=result,
            transcript_ref=None,
        )
        self.turn_log.append(record)

        # Persist the full turn log to disk.
        self._persist_turn_log(data)

        # Update the AnalysisBase artifacts.
        self.analysis_base["objective_summary"] = objective_summary(
            data, self.problem_schema, self.turn_log
        )
        self.analysis_base["coverage_summary"] = coverage_summary(
            data, self.problem_schema, self.turn_log
        )
        self.analysis_base["last_5_rationales"] = last_5_rationales(
            data, self.problem_schema, self.turn_log
        )

        # Check for three consecutive error turns.
        if self._consecutive_errors() >= 3:
            raise AgentExecutionError(
                "AgentOptimizer aborted: three consecutive turns returned "
                "result='error'. Check agent configuration and prompts."
            )

        return data

    # ------------------------------------------------------------------
    # _early_stop
    # ------------------------------------------------------------------

    def _early_stop(
        self, data: ExperimentData, turn_log: list[TurnRecord]
    ) -> bool:
        """Hook for subclasses to implement early termination.

        Default: always return ``False`` (no early stopping).

        Parameters
        ----------
        data : ExperimentData
            The shared dataset.
        turn_log : list of TurnRecord
            The current turn log.

        Returns
        -------
        bool
            ``True`` to stop the loop early; ``False`` to continue.
        """

        return False

    # ------------------------------------------------------------------
    # narrate
    # ------------------------------------------------------------------

    def narrate(self) -> str:
        """Produce a prose account of objective improvements across turns.

        Walks ``experiment_ids`` in insertion order, tracking the running
        best objective.  For each row that improved the best-so-far, looks
        up the corresponding ``TurnRecord.rationale`` and renders a short
        paragraph.  Skips rows with ``__turn < 0`` (seed rows).

        Returns
        -------
        str
            Multi-paragraph prose.  Empty string if no improvements were
            recorded.
        """

        if not hasattr(self, "problem_schema"):
            return "arm() has not been called yet; no history to narrate."

        direction = self.problem_schema.objective_direction
        objective_name = self.problem_schema.objective_name

        # Build a mapping from turn_id to rationale.
        rationale_by_turn: dict[int, str] = {
            rec.turn_id: rec.rationale for rec in self.turn_log
        }

        # Walk all (data) rows in insertion order.
        # We need the data reference — stored by subclasses during call().
        if not hasattr(self, "_last_data") or self._last_data is None:
            return "No data available yet."

        data: ExperimentData = self._last_data
        best_val: Optional[float] = None
        paragraphs: list[str] = []

        for idx, sample in data.data.items():
            turn_stamp = sample._output_data.get("__turn")
            # Skip seed rows.
            if turn_stamp is None or int(turn_stamp) < 0:
                continue

            obj = sample._output_data.get(objective_name)
            if obj is None:
                continue
            try:
                obj_float = float(obj)
            except (TypeError, ValueError):
                continue
            if obj_float != obj_float:
                continue

            # Check improvement.
            improved = False
            if best_val is None:
                improved = True
            elif direction == "maximize" and obj_float > best_val:
                improved = True
            elif direction == "minimize" and obj_float < best_val:
                improved = True

            if improved:
                best_val = obj_float
                rationale = rationale_by_turn.get(int(turn_stamp), "")
                paragraphs.append(
                    f"experiment_id={idx}: objective improved to "
                    f"{obj_float:.6g} (turn {turn_stamp})."
                    + (f"\n  Rationale: {rationale}" if rationale else "")
                )

        return "\n\n".join(paragraphs) if paragraphs else ""

    # ------------------------------------------------------------------
    # write_deliverable
    # ------------------------------------------------------------------

    def write_deliverable(
        self,
        out_dir: Path | str,
        *,
        baseline_value: Optional[float] = None,
        ceiling_value: Optional[float] = None,
    ) -> Path:
        """Write a self-contained run deliverable folder.

        The folder mirrors what a graduate student would hand in at the
        end of a study: the best design found, the reasoning narrative,
        a reproducibility script, the full provenance log, and a
        snapshot of the final ``ExperimentData``.

        Parameters
        ----------
        out_dir : Path or str
            Destination folder.  Created if it does not exist.
        baseline_value : float, optional
            Competing approach's objective result.  When provided, the
            ``## Comparison`` section states whether the agent beat it.
        ceiling_value : float, optional
            Theoretical maximum reachable in the available data (e.g.
            the pool ceiling).  When provided, the ``## Comparison``
            section shows ``agent_best / ceiling_value`` as a percentage.

        Returns
        -------
        Path
            Absolute path to ``out_dir``.

        Raises
        ------
        RuntimeError
            If ``_last_data`` is ``None``, meaning ``call()`` has not
            been invoked yet.
        """

        if not hasattr(self, "_last_data") or self._last_data is None:
            raise RuntimeError(
                "write_deliverable() must be called after call()."
            )

        out_dir = Path(out_dir).resolve()
        out_dir.mkdir(parents=True, exist_ok=True)

        data = self._last_data

        # ----------------------------------------------------------
        # Locate best design from the live dataset.
        # ----------------------------------------------------------
        objective_name = self.problem_schema.objective_name
        direction = self.problem_schema.objective_direction

        best_idx: Optional[int] = None
        best_val: Optional[float] = None
        for idx, sample in data.data.items():
            obj = sample._output_data.get(objective_name)
            if obj is None:
                continue
            try:
                obj_f = float(obj)
            except (TypeError, ValueError):
                continue
            # Skip NaN.
            if obj_f != obj_f:
                continue
            if best_val is None:
                improved = True
            elif direction == "maximize" and obj_f > best_val:
                improved = True
            elif direction == "minimize" and obj_f < best_val:
                improved = True
            else:
                improved = False
            if improved:
                best_val = obj_f
                best_idx = idx

        # ----------------------------------------------------------
        # Build solution.md
        # ----------------------------------------------------------
        solution_lines: list[str] = ["# Solution\n"]

        if best_idx is None or best_val is None:
            solution_lines.append(
                "No rows were produced during this run; "
                "no best design is available.\n"
            )
        else:
            best_sample = data.data[best_idx]
            solution_lines.append(
                f"Best design found (experiment_id={best_idx}):\n"
            )
            # Input parameter values.
            for col, val in best_sample._input_data.items():
                try:
                    solution_lines.append(f"- **{col}**: {float(val):.6g}")
                except (TypeError, ValueError):
                    solution_lines.append(f"- **{col}**: {val}")
            # Objective value.
            solution_lines.append(
                f"\n**{objective_name}** ({direction}): "
                f"{best_val:.6g}\n"
            )

        # ## Comparison section
        comparison_lines: list[str] = []
        if ceiling_value is not None or baseline_value is not None:
            comparison_lines.append("## Comparison\n")
            if (
                ceiling_value is not None
                and best_val is not None
                and ceiling_value != 0.0
            ):
                pct = 100.0 * best_val / ceiling_value
                comparison_lines.append(
                    f"- Agent best vs. pool ceiling: "
                    f"{best_val:.6g} / {ceiling_value:.6g} "
                    f"= **{pct:.1f}%**"
                )
            if baseline_value is not None and best_val is not None:
                if direction == "maximize":
                    beat = best_val > baseline_value
                else:
                    beat = best_val < baseline_value
                verdict = "beat" if beat else "did not beat"
                comparison_lines.append(
                    f"- Agent {verdict} the baseline "
                    f"({baseline_value:.6g})."
                )
            comparison_lines.append("")

        # ## How the solution was reached
        narration = self.narrate()
        narration_section = (
            "## How the solution was reached\n\n"
            + (narration if narration else "(no objective improvements "
               "were recorded during this run)")
            + "\n"
        )

        # ## Run metadata
        n_turns = len(self.turn_log)
        # Count seed rows (those with __turn == SEED_TURN, i.e. < 0).
        n_seed = sum(
            1
            for sample in data.data.values()
            if int(sample._output_data.get("__turn", 0)) < 0
        )
        n_evaluated = len(data.data) - n_seed
        n_agents = len(self.agents)
        agent_models: list[str] = []
        for agent_name_key, agent_obj in self.agents.items():
            model_id = getattr(agent_obj, "model", None)
            if model_id is None:
                model_id = getattr(agent_obj, "_model", "<unknown>")
            agent_models.append(f"{agent_name_key}: {model_id}")

        metadata_lines: list[str] = [
            "## Run metadata\n",
            f"- Turns recorded: {n_turns}",
            f"- Evaluations (non-seed rows): {n_evaluated}",
            f"- Agents involved: {n_agents}",
        ]
        for model_line in agent_models:
            metadata_lines.append(f"  - {model_line}")
        metadata_lines.append("")

        # Assemble and write solution.md.
        full_solution = (
            "\n".join(solution_lines)
            + "\n"
            + ("\n".join(comparison_lines) + "\n" if comparison_lines else "")
            + narration_section
            + "\n"
            + "\n".join(metadata_lines)
        )
        (out_dir / "solution.md").write_text(full_solution, encoding="utf-8")

        # ----------------------------------------------------------
        # Copy turn_log.jsonl
        # ----------------------------------------------------------
        src_log = data._project_dir / "turn_log.jsonl"
        dest_log = out_dir / "turn_log.jsonl"
        if src_log.exists():
            shutil.copy2(src_log, dest_log)
        else:
            # Write from in-memory log if the file was never flushed.
            lines = [rec.to_json() for rec in self.turn_log]
            dest_log.write_text("\n".join(lines) + "\n", encoding="utf-8")

        # ----------------------------------------------------------
        # Copy experiment_data/ snapshot via f3dasm store()
        # ----------------------------------------------------------
        # store() writes to <project_dir>/experiment_data/; we want it
        # under out_dir/experiment_data/.
        # Temporarily point the data at out_dir so store() puts files
        # in the right place, then restore the original project_dir.
        original_project_dir = data._project_dir
        data.store(out_dir)
        # Restore the original project directory reference.
        data.set_project_dir(original_project_dir, in_place=True)

        # ----------------------------------------------------------
        # Write replicate.py
        # ----------------------------------------------------------
        self._write_replicate_script(out_dir)

        return out_dir

    # ------------------------------------------------------------------
    # _write_replicate_script (internal helper)
    # ------------------------------------------------------------------

    def _write_replicate_script(self, out_dir: Path) -> None:
        """Generate ``replicate.py`` inside ``out_dir``.

        The generated script loads the dataset from the deliverable
        folder, replays every ``strategy_calls`` triple from
        ``turn_log.jsonl`` in turn order using the registered strategy
        adapters (no LLM invoked), and prints the best design.

        Parameters
        ----------
        out_dir : Path
            Directory where ``replicate.py`` will be written.
        """

        # Collect (name, n_steps, params) triples in turn order.
        calls: list[tuple[str, int, dict]] = []
        for rec in self.turn_log:
            for call in rec.strategy_calls:
                calls.append((call[0], call[1], call[2]))

        # Serialise the calls list as a Python JSON-literal source block.
        calls_repr = json.dumps(calls, indent=4)

        objective_name = self.problem_schema.objective_name
        direction = self.problem_schema.objective_direction

        # Build the script using explicit string concatenation so that
        # the indentation of the generated file is unambiguous regardless
        # of the indentation level of this method in the source tree.
        # (textwrap.dedent fails when multi-line f-string interpolations
        # introduce lines with less leading whitespace than the template.)
        script = _build_replicate_script(
            calls_repr=calls_repr,
            objective_name=objective_name,
            direction=direction,
        )
        (out_dir / "replicate.py").write_text(script, encoding="utf-8")

    # ------------------------------------------------------------------
    # _render_context
    # ------------------------------------------------------------------

    def _render_context(self) -> str:
        """Render the AnalysisBase as a single prompt block.

        Concatenates ``objective_summary``, ``coverage_summary``, then
        ``last_5_rationales``.  If the total exceeds 8000 characters,
        truncates ``last_5_rationales`` from the oldest end.

        Returns
        -------
        str
            The rendered context string.
        """

        obj = self.analysis_base.get("objective_summary", "")
        cov = self.analysis_base.get("coverage_summary", "")
        rat = self.analysis_base.get("last_5_rationales", "")

        # Budget enforcement: truncate rationales from the oldest end.
        MAX_CHARS = 8000
        combined_without_rat = (
            f"## Objective Summary\n{obj}\n\n"
            f"## Coverage Summary\n{cov}\n\n"
        )
        remaining = MAX_CHARS - len(combined_without_rat)

        if remaining <= 0:
            logger.warning(
                "_render_context: context exceeds 8000 chars even without "
                "rationales; rationales section omitted."
            )
            rat_section = ""
        elif rat and len(rat) > remaining:
            logger.warning(
                "_render_context: last_5_rationales truncated to fit 8000 "
                "character budget."
            )
            rat_section = (
                "## Recent Rationales (oldest truncated)\n"
                + rat[-remaining:]
            )
        else:
            rat_section = (
                f"## Recent Rationales\n{rat}" if rat else ""
            )

        return combined_without_rat + rat_section

    # ------------------------------------------------------------------
    # _followup_dispatch
    # ------------------------------------------------------------------

    def _followup_dispatch(self, question: str) -> str:
        """Route an Implementer follow-up question to the Strategizer.

        Subclasses that implement the two-agent topology should override
        this method.  The base implementation raises ``NotImplementedError``.

        Parameters
        ----------
        question : str
            The natural-language clarification request.

        Returns
        -------
        str
            The Strategizer's response.

        Raises
        ------
        NotImplementedError
            Always raised in the base class.
        """

        raise NotImplementedError(
            "_followup_dispatch must be implemented by the topology subclass."
        )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _build_problem_schema(
        self, data: ExperimentData, output_name: str
    ) -> ProblemSchema:
        """Derive a ``ProblemSchema`` from the live domain and config.

        Parameters
        ----------
        data : ExperimentData
            The shared dataset (read for domain info).
        output_name : str
            Name of the scalar objective output column.

        Returns
        -------
        ProblemSchema
            Immutable problem description.
        """

        domain = data.domain

        # Collect forbidden names: constant parameters + user extras.
        from ..design.parameter import ConstantParameter
        forbidden: list[str] = [
            name
            for name, param in domain.input_space.items()
            if isinstance(param, ConstantParameter)
        ]
        forbidden.extend(self._forbidden_extra)
        forbidden_set = set(forbidden)

        # Build variable_parameters for non-forbidden, non-constant inputs.
        variable_parameters: dict[str, ParameterSpec] = {}
        from ..design.parameter import (
            CategoricalParameter,
            ContinuousParameter,
            DiscreteParameter,
        )
        for name, param in domain.input_space.items():
            if name in forbidden_set:
                continue
            if isinstance(param, ContinuousParameter):
                variable_parameters[name] = ParameterSpec(
                    kind="continuous",
                    bounds=(param.lower_bound, param.upper_bound),
                    categories=None,
                    log_scale=False,
                )
            elif isinstance(param, DiscreteParameter):
                variable_parameters[name] = ParameterSpec(
                    kind="discrete",
                    bounds=(
                        float(param.lower_bound),
                        float(param.upper_bound),
                    ),
                    categories=None,
                    log_scale=False,
                )
            elif isinstance(param, CategoricalParameter):
                variable_parameters[name] = ParameterSpec(
                    kind="categorical",
                    bounds=None,
                    categories=list(param.categories),
                    log_scale=False,
                )
            # ConstantParameter is already excluded above.

        return ProblemSchema(
            variable_parameters=variable_parameters,
            forbidden_parameters=list(forbidden),
            objective_name=output_name,
            objective_direction=self._objective_direction,
            output_columns=dict(self._output_columns),
            physics_context=self._physics_context,
        )

    @staticmethod
    def _extract_rationale(response: str) -> tuple[str, str]:
        """Extract the ``## Rationale`` section from an agent response.

        Parameters
        ----------
        response : str
            The final assistant message text.

        Returns
        -------
        tuple of (str, str)
            ``(rationale_text, result)`` where ``result`` is ``'ok'`` on
            success or ``'error'`` if no ``## Rationale`` section exists.
        """

        marker = "## Rationale"
        idx = response.find(marker)
        if idx == -1:
            return "", "error"
        # Everything after the marker heading line.
        after = response[idx + len(marker):]
        # Trim leading newline.
        rationale = after.lstrip("\n").strip()
        # Stop at the next heading.
        next_heading = rationale.find("\n##")
        if next_heading != -1:
            rationale = rationale[:next_heading].strip()
        return rationale, "ok"

    def _persist_turn_log(self, data: ExperimentData) -> None:
        """Write the full turn log to ``<project_dir>/turn_log.jsonl``.

        Parameters
        ----------
        data : ExperimentData
            Used to locate the project directory.
        """

        project_dir: Path = data._project_dir
        log_path = project_dir / "turn_log.jsonl"
        lines = [record.to_json() for record in self.turn_log]
        log_path.write_text("\n".join(lines) + "\n")

    def _consecutive_errors(self) -> int:
        """Count the number of trailing ``result='error'`` entries in the log.

        Returns
        -------
        int
            Length of the trailing error run.
        """

        count = 0
        for record in reversed(self.turn_log):
            if record.result == "error":
                count += 1
            else:
                break
        return count


# =============================================================================
# ClaudeSDKAgent
# =============================================================================


class ClaudeSDKAgent:
    """Concrete ``Agent`` wrapping an Anthropic Claude Agent SDK session.

    The session maintains conversation history across ``send()`` calls via
    the Claude Agent SDK's ``resume`` mechanism: each call stores the
    returned ``session_id`` and passes it as ``resume=`` on the next call
    so the subprocess picks up where it left off.

    Parameters
    ----------
    name : str
        Stable identifier (e.g. ``'strategizer'``).
    system_prompt : str
        The 4-field system prompt built by the topology.
    deny_list : list of str, optional
        Tool names to block at the SDK level (``disallowed_tools``).
    model : str, optional
        Claude model identifier; defaults to ``claude-haiku-4-5-20251001``.
    **sdk_kwargs : Any
        Extra keyword arguments forwarded to ``ClaudeAgentOptions``.

    Notes
    -----
    ``claude-agent-sdk`` is imported lazily so that f3dasm without the
    agentic extras can still import without raising ``ImportError``.

    Tools (Python callables) are wrapped into an in-process MCP server via
    ``create_sdk_mcp_server()`` on every ``send()`` call.  The MCP server
    name is derived from the agent name so it is stable across calls.

    The implementation is synchronous (``asyncio.run(...)`` bridges into
    the async SDK) because ``send()`` is called from synchronous
    orchestration code.
    """

    def __init__(
        self,
        name: str,
        system_prompt: str,
        deny_list: list[str] = (),
        model: str = "claude-haiku-4-5-20251001",
        **sdk_kwargs: Any,
    ) -> None:
        """Initialise the Claude Agent SDK wrapper.

        Parameters
        ----------
        name : str
            Stable identifier.
        system_prompt : str
            Agent system prompt forwarded to ``ClaudeAgentOptions``.
        deny_list : list of str, optional
            Tool names to block via ``disallowed_tools``.
        model : str, optional
            Claude model identifier.
        **sdk_kwargs : Any
            Extra kwargs forwarded to ``ClaudeAgentOptions``.
        """

        self.name = name
        self._system_prompt = system_prompt
        self._model = model
        self._deny_list = list(deny_list)
        self._sdk_kwargs = sdk_kwargs

        # Lazy import — raises ImportError only when a ClaudeSDKAgent is
        # actually constructed in an environment without the SDK installed.
        try:
            import claude_agent_sdk  # noqa: F401
            self._sdk_available = True
        except ImportError:
            self._sdk_available = False
            warnings.warn(
                "claude-agent-sdk package not found; "
                "ClaudeSDKAgent.send() will raise ImportError. "
                "Install it with: pip install 'f3dasm[agentic]' "
                "or use StubAgent for testing.",
                ImportWarning,
                stacklevel=2,
            )

        # Session ID returned by the last query(); used for resume= on the
        # next call so the CLI subprocess picks up the full conversation.
        self._session_id: Optional[str] = None

        # Conversation history maintained across send() calls.
        # Kept for diagnostics and potential fallback; primary persistence
        # is the CLI session referenced by self._session_id.
        self._history: list[dict[str, Any]] = []

    # ------------------------------------------------------------------
    # send
    # ------------------------------------------------------------------

    def send(self, message: str, tools: list) -> str:
        """Send a message to the Claude session and return its response.

        Conversation history is preserved across calls via the Claude Agent
        SDK's session-resume mechanism: the ``session_id`` returned by each
        ``query()`` run is stored in ``self._session_id`` and passed as
        ``resume=`` on the next call.

        Parameters
        ----------
        message : str
            The orchestrator's turn message sent to the agent.
        tools : list
            Per-turn tool callables to expose to the agent.  Each entry
            must be a Python callable whose ``__name__`` is a unique tool
            identifier and whose ``__doc__`` is used as the tool description.
            Parameter types are introspected from ``inspect.signature``; all
            parameters are mapped to ``str`` (JSON Schema ``"string"``) when
            the annotation is absent or cannot be resolved.

        Returns
        -------
        str
            Final assistant message text; concatenation of all
            ``TextBlock.text`` values from the last ``AssistantMessage``
            received before the ``ResultMessage``.

        Raises
        ------
        ImportError
            If ``claude-agent-sdk`` is not installed.
        RuntimeError
            If the SDK query returns an error result or emits no assistant
            text.
        """

        import asyncio
        import inspect

        # Raise early if the SDK is not available.
        if not self._sdk_available:
            raise ImportError(
                "claude-agent-sdk is required for ClaudeSDKAgent.send(). "
                "Install it with: pip install 'f3dasm[agentic]'"
            )

        from claude_agent_sdk import (
            AssistantMessage,
            ClaudeAgentOptions,
            ResultMessage,
            SdkMcpTool,
            TextBlock,
            create_sdk_mcp_server,
            query,
        )

        # ----------------------------------------------------------------
        # Build an in-process MCP server from the per-turn tool callables.
        # Each callable becomes one SdkMcpTool; the handler is a thin async
        # wrapper that calls the underlying synchronous Python function and
        # returns its result as MCP content text.
        # ----------------------------------------------------------------

        def _infer_schema(fn: Any) -> dict[str, Any]:
            """Derive a simple JSON Schema dict from ``fn``'s signature."""
            sig = inspect.signature(fn)
            props: dict[str, Any] = {}
            required: list[str] = []
            for pname, param in sig.parameters.items():
                ann = param.annotation
                if ann is inspect.Parameter.empty or ann is None:
                    # Fall back to string when annotation is absent.
                    json_type: dict[str, Any] = {"type": "string"}
                elif ann is int:
                    json_type = {"type": "integer"}
                elif ann is float:
                    json_type = {"type": "number"}
                elif ann is bool:
                    json_type = {"type": "boolean"}
                elif ann is dict:
                    json_type = {"type": "object"}
                elif ann is list:
                    json_type = {"type": "array"}
                else:
                    json_type = {"type": "string"}
                props[pname] = json_type
                if param.default is inspect.Parameter.empty:
                    required.append(pname)
            schema: dict[str, Any] = {
                "type": "object",
                "properties": props,
            }
            if required:
                schema["required"] = required
            return schema

        sdk_tools: list[SdkMcpTool] = []
        for fn in tools:
            # Capture fn in a closure so the async handler binds the
            # correct callable (not the last value of fn at loop end).
            def _make_handler(bound_fn: Any) -> Any:
                async def _handler(args: dict[str, Any]) -> dict[str, Any]:
                    try:
                        result = bound_fn(**args)
                    except Exception as exc:
                        return {
                            "content": [
                                {
                                    "type": "text",
                                    "text": (
                                        f"Tool {bound_fn.__name__} raised "
                                        f"{type(exc).__name__}: {exc}"
                                    ),
                                }
                            ],
                            "is_error": True,
                        }
                    return {
                        "content": [
                            {
                                "type": "text",
                                "text": (
                                    str(result)
                                    if result is not None
                                    else ""
                                ),
                            }
                        ]
                    }

                return _handler

            sdk_tools.append(
                SdkMcpTool(
                    name=fn.__name__,
                    description=(
                        (fn.__doc__ or fn.__name__).split("\n")[0].strip()
                    ),
                    input_schema=_infer_schema(fn),
                    handler=_make_handler(fn),
                )
            )

        # Stable server name derived from agent name; one server per agent.
        server_name = f"f3dasm_{self.name}_tools"

        # Build an in-process MCP server config (or an empty one if no tools
        # were provided on this turn).
        mcp_config = create_sdk_mcp_server(
            name=server_name,
            tools=sdk_tools if sdk_tools else None,
        )

        # ----------------------------------------------------------------
        # Build the tool allow-list from the registered tool names so the
        # SDK does not prompt the user to approve each tool invocation.
        # ----------------------------------------------------------------
        tool_names = [t.name for t in sdk_tools]

        # ----------------------------------------------------------------
        # Configure the SDK options.
        # ----------------------------------------------------------------
        options = ClaudeAgentOptions(
            system_prompt=self._system_prompt,
            model=self._model,
            mcp_servers={server_name: mcp_config},
            # Allow every tool registered in the per-turn MCP server without
            # interactive permission prompts.
            allowed_tools=tool_names,
            # Block any tool on the deny-list (e.g. Bash, Write).
            disallowed_tools=self._deny_list,
            # Resume the existing CLI session so conversation history is
            # preserved across send() calls.  On the first call (_session_id
            # is None) a fresh session is started.
            resume=self._session_id,
            # Only load user/project settings that are relevant; skip local
            # settings so the SDK runs in a predictable state.
        )

        # ----------------------------------------------------------------
        # Drive the async query() via asyncio.run().
        # Collect AssistantMessage blocks and the final ResultMessage.
        # ----------------------------------------------------------------
        assistant_texts: list[str] = []
        result_msg: Optional[ResultMessage] = None

        async def _run() -> None:
            nonlocal result_msg
            last_assistant: Optional[AssistantMessage] = None
            async for msg in query(prompt=message, options=options):
                if isinstance(msg, AssistantMessage):
                    last_assistant = msg
                elif isinstance(msg, ResultMessage):
                    result_msg = msg
                    # Extract text from the last AssistantMessage before
                    # the ResultMessage.
                    if last_assistant is not None:
                        for block in last_assistant.content:
                            if isinstance(block, TextBlock):
                                assistant_texts.append(block.text)
                    break

        asyncio.run(_run())

        # ----------------------------------------------------------------
        # Persist the session_id so the next send() can resume the session.
        # ----------------------------------------------------------------
        if result_msg is not None:
            self._session_id = result_msg.session_id

        # ----------------------------------------------------------------
        # Persist the turn in the local history list for diagnostics.
        # ----------------------------------------------------------------
        self._history.append({"role": "user", "content": message})
        combined = "".join(assistant_texts)
        if combined:
            self._history.append({"role": "assistant", "content": combined})

        # ----------------------------------------------------------------
        # Raise if the SDK reported an error result.
        # ----------------------------------------------------------------
        if result_msg is not None and result_msg.is_error:
            raise RuntimeError(
                f"ClaudeSDKAgent '{self.name}': SDK query returned an error. "
                f"Result: {result_msg}"
            )

        if not combined:
            logger.warning(
                "ClaudeSDKAgent '%s': query returned no assistant text. "
                "Returning empty string.",
                self.name,
            )

        return combined


# =============================================================================
# StrategizerImplementerOptimizer
# =============================================================================


class StrategizerImplementerOptimizer(AgentOptimizer):
    """Level-1 two-agent topology: Strategizer proposes, Implementer executes.

    A single logical iteration produces two ``TurnRecord``s (one per agent)
    and possibly more if the Implementer calls ``ask_strategizer``.

    Parameters
    ----------
    strategizer_factory : callable
        Called with ``name=`` and ``system_prompt=`` (and any extras) to
        instantiate the Strategizer agent.
    implementer_factory : callable
        Called with ``name=`` and ``system_prompt=`` to instantiate the
        Implementer agent.
    physics_context : str
        Day-1 problem briefing.
    output_columns : dict[str, OutputSpec]
        Typed metadata for every output column.
    extra_strategies : list of StrategySpec, optional
        Additional strategy specs to merge into the registry.
    extra_adapters : dict[str, callable], optional
        Corresponding adapter callables for ``extra_strategies``.
    forbidden_extra : list of str, optional
        Extra forbidden parameter names.
    max_followups : int, default 2
        Maximum number of ``ask_strategizer`` round-trips per Implementer
        turn.
    objective_direction : {'minimize', 'maximize'}, default 'maximize'
        Direction of optimization.
    """

    def __init__(
        self,
        strategizer_factory: Callable[..., Agent],
        implementer_factory: Callable[..., Agent],
        physics_context: str,
        output_columns: dict[str, OutputSpec],
        extra_strategies: list[StrategySpec] = (),
        extra_adapters: Optional[dict[str, Callable]] = None,
        forbidden_extra: list[str] = (),
        max_followups: int = 2,
        objective_direction: ObjectiveDirection = "maximize",
    ) -> None:
        """Initialise the topology.

        Parameters
        ----------
        strategizer_factory : callable
            Factory for the Strategizer agent.
        implementer_factory : callable
            Factory for the Implementer agent.
        physics_context : str
            Day-1 problem briefing.
        output_columns : dict[str, OutputSpec]
            Typed metadata for every output column.
        extra_strategies : list of StrategySpec, optional
            Additional strategies to register.
        extra_adapters : dict[str, callable], optional
            Adapters corresponding to ``extra_strategies``.
        forbidden_extra : list of str, optional
            Extra forbidden parameter names.
        max_followups : int, default 2
            Follow-up budget per Implementer turn.
        objective_direction : {'minimize', 'maximize'}, default 'maximize'
            Direction of optimization.
        """

        super().__init__(
            physics_context=physics_context,
            output_columns=output_columns,
            forbidden_extra=forbidden_extra,
            objective_direction=objective_direction,
        )
        self._strategizer_factory = strategizer_factory
        self._implementer_factory = implementer_factory
        self._extra_strategies: list[StrategySpec] = list(extra_strategies)
        self._extra_adapters: dict[str, Callable] = (
            dict(extra_adapters) if extra_adapters else {}
        )
        self.max_followups = max_followups

        # Holds the data reference so narrate() can find it after call().
        self._last_data: Optional[ExperimentData] = None

        # Monotonic turn counter; managed by call().
        self._current_turn_id: int = 0

    # ------------------------------------------------------------------
    # arm
    # ------------------------------------------------------------------

    def arm(
        self,
        data: ExperimentData,
        data_generator: DataGenerator,
        input_name: str,
        output_name: str,
    ) -> None:
        """Arm the topology: build the registry and instantiate agents.

        Parameters
        ----------
        data : ExperimentData
            The shared dataset.
        data_generator : DataGenerator
            The evaluator.
        input_name : str
            Input parameter group name.
        output_name : str
            Objective output column name.
        """

        super().arm(data, data_generator, input_name, output_name)

        # Merge extra strategies into the registry.
        for spec in self._extra_strategies:
            self.strategy_specs[spec.name] = spec
        for name, adapter in self._extra_adapters.items():
            self.strategy_adapters[name] = adapter

        # Compose per-agent system prompts.
        strategizer_prompt = self._compose_strategizer_prompt(
            self.problem_schema
        )
        implementer_prompt = self._compose_implementer_prompt(
            self.problem_schema
        )

        # Instantiate the two persistent peer agents.
        self.agents = {
            "strategizer": self._strategizer_factory(
                name="strategizer",
                system_prompt=strategizer_prompt,
            ),
            "implementer": self._implementer_factory(
                name="implementer",
                system_prompt=implementer_prompt,
            ),
        }

    # ------------------------------------------------------------------
    # call
    # ------------------------------------------------------------------

    def call(
        self, data: ExperimentData, n_iterations: int, **kwargs: Any
    ) -> ExperimentData:
        """Run the Strategizer → Implementer loop for ``n_iterations``.

        Each logical iteration produces at least two ``TurnRecord``s
        (Strategizer + Implementer), plus additional Strategizer records
        for any ``ask_strategizer`` follow-ups.

        Parameters
        ----------
        data : ExperimentData
            The shared dataset.
        n_iterations : int
            Maximum number of logical iterations.
        **kwargs : Any
            Ignored; accepted for signature compatibility.

        Returns
        -------
        ExperimentData
            The updated (mutated-in-place) dataset.
        """

        self._last_data = data
        turn_id = self._current_turn_id

        for _iteration in range(n_iterations):
            # ---------------------------------------------------------
            # Strategizer turn
            # ---------------------------------------------------------
            ctx = self._compose_turn_message(turn_id)
            data = self._execute_turn(turn_id, "strategizer", ctx, data)
            turn_id += 1

            # Retrieve the emitted strategy from the previous record.
            strat_record = self.turn_log[-1]
            strategy = strat_record.emitted_strategy

            if strategy is None:
                logger.warning(
                    "Strategizer turn %d did not emit a strategy; "
                    "skipping Implementer turn.",
                    turn_id - 1,
                )
                continue

            # ---------------------------------------------------------
            # Implementer turn
            # ---------------------------------------------------------
            impl_msg = self._compose_implementer_message(
                turn_id, strategy
            )
            data = self._execute_turn(turn_id, "implementer", impl_msg, data)
            turn_id += 1

            # Store the current turn_id for follow-up routing.
            self._current_turn_id = turn_id

            if self._early_stop(data, self.turn_log):
                break

        self._current_turn_id = turn_id
        return data

    # ------------------------------------------------------------------
    # _followup_dispatch
    # ------------------------------------------------------------------

    def _followup_dispatch(self, question: str) -> str:
        """Route a clarification question to the Strategizer.

        Called by the ``ask_strategizer`` tool closure during an
        Implementer turn.  Each call increments the turn counter and
        produces a new Strategizer ``TurnRecord``.

        Parameters
        ----------
        question : str
            The Implementer's clarification request.

        Returns
        -------
        str
            The Strategizer's rationale (from the ``## Rationale`` section
            of its response).
        """

        if self._last_data is None:
            return "ERROR: no active data; followup dispatch not possible."

        turn_id = self._current_turn_id
        ctx = self._compose_turn_message(turn_id)
        followup_msg = (
            f"{ctx}\n\n---\nThe Implementer asks:\n{question}\n"
            "Please respond with your clarification under "
            "## Rationale."
        )

        self._execute_turn(
            turn_id, "strategizer", followup_msg, self._last_data
        )
        self._current_turn_id = turn_id + 1

        # Return the Strategizer's rationale as the response.
        if self.turn_log:
            return self.turn_log[-1].rationale or ""
        return ""

    # ------------------------------------------------------------------
    # Prompt composers
    # ------------------------------------------------------------------

    def _compose_strategizer_prompt(
        self, schema: ProblemSchema
    ) -> str:
        """Compose the 4-field system prompt for the Strategizer.

        Parameters
        ----------
        schema : ProblemSchema
            The immutable problem description.

        Returns
        -------
        str
            The system prompt string.
        """

        variables_text = self._render_variable_parameters(schema)
        outputs_text = self._render_output_columns(schema)
        strategies_text = ", ".join(sorted(self.strategy_specs.keys()))

        return (
            "## Title\n"
            "DOE Strategy Specialist\n\n"
            "## Expertise\n"
            "Bayesian optimization, design of experiments, "
            "exploration-exploitation tradeoffs over engineering "
            "design spaces.\n\n"
            f"## Problem Context\n{schema.physics_context}\n\n"
            "## Goal\n"
            f"Choose the next strategy to advance the objective "
            f"('{schema.objective_name}', direction: "
            f"{schema.objective_direction}), given what is known.\n\n"
            "## Variable Parameters\n"
            f"{variables_text}\n\n"
            "## Output Columns\n"
            f"{outputs_text}\n\n"
            "## Available Strategies\n"
            f"{strategies_text}\n\n"
            "## Role\n"
            "Each turn, read the orchestrator-provided context. "
            "Pick a strategy from the registry and build a Strategy "
            "payload with a substantive intent. Emit it via "
            "emit_strategy. Return your reasoning under ## Rationale."
        )

    def _compose_implementer_prompt(
        self, schema: ProblemSchema
    ) -> str:
        """Compose the 4-field system prompt for the Implementer.

        Parameters
        ----------
        schema : ProblemSchema
            The immutable problem description.

        Returns
        -------
        str
            The system prompt string.
        """

        variables_text = self._render_variable_parameters(schema)
        outputs_text = self._render_output_columns(schema)

        return (
            "## Title\n"
            "DOE Execution Specialist\n\n"
            "## Expertise\n"
            "Parameterising samplers and optimizers correctly; "
            "interpreting their summary outputs.\n\n"
            f"## Problem Context\n{schema.physics_context}\n\n"
            "## Goal\n"
            "Execute the Strategy handed by the Strategizer; "
            "report what happened.\n\n"
            "## Variable Parameters\n"
            f"{variables_text}\n\n"
            "## Output Columns\n"
            f"{outputs_text}\n\n"
            "## Role\n"
            "Each turn, read the Strategy payload. If anything is "
            "unclear, call ask_strategizer. Otherwise call "
            "run_strategy(name, n_steps, params) and return your "
            "reasoning under ## Rationale."
        )

    # ------------------------------------------------------------------
    # Message composers
    # ------------------------------------------------------------------

    def _compose_turn_message(self, turn_id: int) -> str:
        """Render the context block for a Strategizer turn.

        Parameters
        ----------
        turn_id : int
            Current turn index.

        Returns
        -------
        str
            The turn message string.
        """

        context = self._render_context()
        if turn_id == 0:
            preamble = (
                f"Turn {turn_id}. No evaluations have happened yet. "
                "State of the world below."
            )
        else:
            preamble = f"Turn {turn_id}. State of the world below."
        return f"{preamble}\n\n{context}"

    def _compose_implementer_message(
        self, turn_id: int, strategy: Strategy
    ) -> str:
        """Render the Implementer's turn message including the Strategy.

        Parameters
        ----------
        turn_id : int
            Current turn index.
        strategy : Strategy
            The Strategy payload emitted by the Strategizer.

        Returns
        -------
        str
            The turn message string.
        """

        context = self._render_context()
        strategy_block = (
            "## Strategy from Strategizer\n"
            f"Name: {strategy.name}\n"
            f"Steps: {strategy.n_steps}\n"
            f"Params: {json.dumps(strategy.params)}\n\n"
            f"### Intent\n{strategy.intent}"
        )
        preamble = f"Turn {turn_id}. Execute the following strategy."
        return f"{preamble}\n\n{context}\n\n{strategy_block}"

    # ------------------------------------------------------------------
    # Schema rendering helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _render_variable_parameters(schema: ProblemSchema) -> str:
        """Render variable parameters as a compact text block.

        Parameters
        ----------
        schema : ProblemSchema
            The problem description.

        Returns
        -------
        str
            Multi-line text.
        """

        if not schema.variable_parameters:
            return "(none)"
        lines: list[str] = []
        for name, spec in schema.variable_parameters.items():
            if spec.kind == "categorical" and spec.categories:
                lines.append(
                    f"  {name} (categorical): {spec.categories}"
                )
            elif spec.bounds is not None:
                lo, hi = spec.bounds
                scale = " [log-scale]" if spec.log_scale else ""
                lines.append(
                    f"  {name} ({spec.kind}): [{lo:g}, {hi:g}]{scale}"
                )
            else:
                lines.append(f"  {name} ({spec.kind})")
        return "\n".join(lines)

    @staticmethod
    def _render_output_columns(schema: ProblemSchema) -> str:
        """Render output columns as a compact text block.

        Parameters
        ----------
        schema : ProblemSchema
            The problem description.

        Returns
        -------
        str
            Multi-line text.
        """

        if not schema.output_columns:
            return "(none)"
        lines: list[str] = []
        for name, spec in schema.output_columns.items():
            desc = f" — {spec.description}" if spec.description else ""
            if spec.kind == "categorical" and spec.categories:
                lines.append(
                    f"  {name} (categorical, {spec.categories}){desc}"
                )
            else:
                lines.append(f"  {name} (continuous){desc}")
        return "\n".join(lines)


__all__ = [
    "Agent",
    "AgentExecutionError",
    "AgentOptimizer",
    "ClaudeSDKAgent",
    "StrategizerImplementerOptimizer",
]
