# This configuration file defines the default logging behavior of f3dasm.
#
#                                                          Authorship & Credits
# =============================================================================
# __author__ = 'Guillaume Broggi (g.broggi@tudelft.nl)'
# __credits__ = ['Guillaume Broggi']
# __status__ = 'Stable'
# =============================================================================
#
version: 1
disable_existing_loggers: False 
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stderr
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: f3dsam.log
    maxBytes: 10485760 # 10MB
    backupCount: 5 # After reaching maxBytes, a new file is opened
    encoding: utf8
    mode: w # is ignored and forced to "a" with RotatingFileHandler
loggers:
  f3dsam:
    level: INFO
    handlers: [console, file]
    propagate: no


