defaults:
  - default

design:
  lower_bound: -3.0
  upper_bound: 3.5
  dimensionality: 2

function:
  function_name: Levy

optimizer:
  optimizer_name: Nadam

sampler:
  sampler_name: LatinHypercube
  number_of_samples: 30

execution:
  iterations: 140
  realizations: 6
  parallelization: True