hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +trial_number: range(1)
  sweep:
    dir: outputs/default/${optimizer.optimizer_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: trial_${trial_number}
  job:
    chdir: True

design:
  lower_bound: 0.0
  upper_bound: 1.0
  dimensionality: 1

functions:
  function_names: [
    AlpineN1,
  ]
  noise: None

optimizer:
  optimizer_name: BayesianOptimizationTorch

sampler:
  sampler_name: SobolSequence
  number_of_samples: 5

execution:
  iterations: 20