hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +trial_number: range(1)
      +design.dimensionality: range(1, 4)
  sweep:
    dir: outputs/default/${optimizer.optimizer_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: dim_${design.dimensionality}/trial_${trial_number}
  job:
    chdir: True
  # hydra_logging: disabled
  # job_logging: disabled

design:
  lower_bound: 0.0
  upper_bound: 1.0

functions:
  function_names: [
    AlpineN1,
    AlpineN2,
  ]
  noise: None

optimizer:
  optimizer_name: BayesianOptimizationTorch

sampler:
  sampler_name: SobolSequence
  number_of_samples: ${eval:'2 ** ${design.dimensionality}'}

execution:
  iterations: ${eval:'5 * 2 ** ${design.dimensionality}'}
  seed: 123