hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +trial_number: range(1)
  sweep:
    dir: outputs/${optimizer.optimizer_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: trial_${trial_number}
  job:
    chdir: True

defaults:
  - default

design:
  lower_bound: 0.0
  upper_bound: 1.0
  dimensionality: 1

functions:
  function_names: [
    AlpineN1,
    AlpineN2,
    Ackley,
    DixonPrice,
    Exponential,
    Griewank,
    HappyCat,
    Periodic,
    PermDBeta,
    PermZeroDBeta,
    Powell,
    Qing,
    Rastrigin,
    Ridge,
    RotatedHyperEllipsoid,
    Salomon,
    Schwefel,
    Schwefel2_20,
    Schwefel2_21,
    Schwefel2_22,
    Schwefel2_23,
    Sphere,
    StyblinskiTank,
    SumSquares,
    Trid,
    XinSheYangN2,
    XinSheYangN3,
    XinSheYangN4,
    Zakharov,
  ]
  noise: None

optimizer:
  optimizer_name: BayesianOptimizationTorch

sampler:
  sampler_name: SobolSequence
  number_of_samples: 5

execution:
  iterations: 20