defaults:
  - default

design:
  lower_bound: -1.0
  upper_bound: 1.0
  dimensionality: 3

function:
  function_name: Levy

optimizers:
  optimizers_names: [
    Adam,
    SGD,
    CG,
    CMAES,
    DifferentialEvolution,
    DualAnnealing,
    LBFGSB,
    NelderMead,
    PSO,
    RandomSearch,
    SGA,
    XNES,
    RMSprop,
    Nadam,
    Adamax,
    Ftrl,
  ]

sampler:
  sampler_name: LatinHypercube
  number_of_samples: 30

execution:
  iterations: 500
  realizations: 5
  parallelization: True